### PR TITLE
Fixed collapse behavior

### LINKED ISSUE #724: Collapsing/expanding any facet panel results in the top panel being collapsed/expanded
I noticed this early this morning and didn't find it on the list of issues - it's reproducible on all deployments.

http://i.imgur.com/KDxGVB2.gifv

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #724

### CODE REVIEW

**Comment by giocalitri** [comment]
This looks good. 
Should we add some tests? Is it worth?

**Comment by noisecapella** [comment]
This is difficult to test since it relies on bootstrap magic to work. But we can always assert the id attribute at least. I'll do that

**Comment by noisecapella** [comment]
Tests are in, I'll merge once tests pass

**Comment by giocalitri** [comment]
:+1:

**Pull request merged**
