### PR TITLE
Replaced default missing title and updated description path

### LINKED ISSUE #604: Use elipsis (...) instead of MISSING in learning resource path when display_name isn't set
As a user, the repeated MISSING that appears in learning resource paths in the list view is distracting. Can we use something like `...` instead?

screenshot-lore-ci herokuapp com 2015-09-08 11-11-08

we only want to change the path, not the learning resource name. It would be best to change the existing path data, as well as any new path data.

### PR DESCRIPTION
**Pull request by giocalitri**
Closes #604 

Depends on #705

### CODE REVIEW

**Comment by noisecapella** [comment]
When running the migrations I got this error:

```
  Applying learningresources.0017_learningresource_missing_title_update...No handlers could be found for logger "elasticsearch.trace"
Traceback (most recent call last):
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/src/learningresources/migrations/0017_learningresource_missing_title_update.py", line 24, in replace_missing_title
    learning_resource.save()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/src/search/signals.py", line 64, in handle_resource_update
    index_resources([instance])
  File "/usr/local/lib/python2.7/dist-packages/statsd/client.py", line 30, in _wrapped
    return_value = f(*args, **kwargs)
  File "/src/search/utils.py", line 116, in index_resources
    ensure_vocabulary_mappings(term_info)
  File "/src/search/utils.py", line 348, in ensure_vocabulary_mappings
    mapping = Mapping.from_es(index=INDEX_NAME, doc_type=DOC_TYPE)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/mapping.py", line 38, in from_es
    m.update_from_es(index, using)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/mapping.py", line 82, in update_from_es
    _, raw = raw.popitem()
KeyError: 'popitem(): dictionary is empty'
```

**Comment by ShawnMilo** [comment]
Thanks, @noisecapella. Maybe I need to blow out everything and run migrations from scratch. It looks like it happens if you don't have an old version of the mapping.

**Comment by giocalitri** [comment]
@ShawnMilo What should I do with the stack trace? Should I consider it as part of this PR?

**Comment by ShawnMilo** [comment]
@giocalitri The stack trace should be fixed before this is merged, certainly. I suspect that if it can happen to one of you, it can happen in lore-ci, which would be bad.

**Comment by giocalitri** [comment]
@noisecapella did you have a clean environment or starting from an existing one?

**Comment by noisecapella** [comment]
Existing, just whatever was in my docker container at the time. I did a reindex right before the migrate if that matters

**Comment by ShawnMilo** [comment]
For the record, my comments above are due to me being confused and thinking we were discussing my PR, #718. Based on the error message, though, it is definitely due to the elasticsearch-py code I added in a previous branch.

**Comment by ShawnMilo** [comment]
@noisecapella: Can you reliably reproduce that error when running migrations?

Since it's not broken in Lore-CI or Lore-RC, I don't know why it's happening yet.

**Comment by noisecapella** [comment]
I checked out the latest from this PR and migrations appear to succeed now

**Comment by giocalitri** [comment]
Tried a couple of approaches to reproduce it, but I did not have any luck

**Comment by giocalitri** [comment]
I will leave as it is unless someone else can reproduce the error

**Comment by noisecapella** [comment]
Can you add a transaction around the management command? Other than that this looks fine

**Comment by giocalitri** [comment]
why the transaction?

**Comment by noisecapella** [comment]
So if the management command fails halfway through it won't leave the job half done which would be confusing.

**Comment by giocalitri** [comment]
done

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
