### PR TITLE
Release 0.14.1

### PR DESCRIPTION
**Pull request by pwilkins**
Release v0.14.1
- Made `requires.io` dependency update.
- Added manual test plan.
- Made changes to accommodate Docker 1.9.0.

### CODE REVIEW

**Comment by bdero** [comment]
It looks like these changes already got pushed to the release-candidate branch.

**Comment by pdpinch** [comment]
I think that's been our process -- is that a problem?

**Comment by bdero** [comment]
Nope, but what's this PR for?

**Comment by bdero** [comment]
Ah, so the process is that the `rc/` branch is merged into `master` rather than `release` into `master`? We might want to merge `release` into `master` after `release` is verified deployed instead - just so we can catch any possible deviation between `release` and `master` in the PR.

**Pull request closed without merging**
