### PR TITLE
Fixing memory usage in migration

### PR DESCRIPTION
**Pull request by giocalitri**

### CODE REVIEW

**Comment by bdero** [comment]
Looks good once tests pass. :+1:

**Comment by noisecapella** [comment]
What does this do? Wouldn't we want our migrations to be wrapped in transactions?

**Comment by giocalitri** [comment]
we are having problems with the memory during transactions

**Comment by bdero** [comment]
We might want to take the conversation over here instead of in the Lore room, but @giocalitri is currently testing if the large transaction being built by this migration is the cause of a steep linear memory increase I'm seeing on the dyno trying to run this migration.
Since the actions of this migration are idempotent, there shouldn't be problems if the migration is killed while in the middle of running.

That being said, this shouldn't be merged until we know that it's the transaction and not something else.

**Comment by giocalitri** [comment]
The atomic kwarg itself does not solve the problem, I modified the code to avoid to load the entire queryset in memory
I tested it and it should work: before the memory was spiking; now it raises but does not go at the same levels I saw before

**Comment by giocalitri** [comment]
We may want to remove the `atomic=False` since I think the new code should take care of the problem

**Comment by bdero** [comment]
Ah, good - let's add the transaction back, then.

**Comment by giocalitri** [comment]
Done

**Comment by noisecapella** [comment]
The `.all` is still there. You may be able to just do `objects.order_by('id').iterator()`, not sure if it makes a difference however.

**Comment by giocalitri** [comment]
@noisecapella as far as I remember the `.all` should not actually pull the data until you access the objects, so it just builds a queryset and querysets are lazy (see [here](https://docs.djangoproject.com/en/1.8/topics/db/optimization/#understand-queryset-evaluation))

**Comment by noisecapella** [comment]
Sounds good to me

**Comment by giocalitri** [comment]
actually you are right

**Comment by giocalitri** [comment]
I'm going to change the code following @noisecapella suggestion (thanks!)

**Comment by giocalitri** [comment]
Reading the documentation carefully, I think I was right (just misunderstood one part of it), but in any case I removed the `.all` because it's useless. Merging now.

**Pull request merged**
