### PR TITLE
Fixed error message on unsupported terms in learning resource

### PR DESCRIPTION
**Pull request by noisecapella**
Looks like I missed an argument during `format()`

### CODE REVIEW

**Comment by pwilkins** [comment]
@noisecapella Is there a way for me to verify this change?  I can merge it without verification, but I wonder if there is even a way to see this validation message in action.

**Comment by noisecapella** [comment]
You would need to add a vocabulary and a term then PATCH /api/v1/repositories/repo/learning_resources/1 with {'terms': ['new_term_slug']} to get the error message.

**Comment by ShawnMilo** [comment]
This was accidentally closed in PR #397 (I meant to close 318, typed 316 instead).

@noisecapella, @pwilkins it looks like this was already merged, so is it good to leave this closed?

**Comment by noisecapella** [comment]
Yes, should be fine

**Pull request merged**
