### PR TITLE
Added debug_toolbar

### LINKED ISSUE #730: Install and use Django Debug Toolbar
This would help in quick investigation of performance problems. I think it requires a Python package and a name in `INSTALLED_APPS`

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #730

### CODE REVIEW

**Comment by noisecapella** [comment]
BTW I needed to add 

```
INTERNAL_IPS = ('172.17.42.1',)
```

to get it to turn on and work with the docker container. I could add this as part of the docker environment variables if it works for boot2docker too.

**Comment by giocalitri** [comment]
I'm not sure that IP is stable.

**Comment by noisecapella** [comment]
It looks like we can figure out the IP using this command (from [here](http://blog.michaelhamrah.com/2014/06/accessing-the-docker-host-server-within-a-container/)):

```
netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}'
```

I'll look into updating this PR to create an environment variable for that and populating `INTERNAL_IPS`

**Comment by noisecapella** [comment]
This is basically done except that the session expires really frequently, need to investigate before this gets merged.

**Comment by ShawnMilo** [comment]
In my experience, session problems like that are often due to a clock issue.

If not, check out what the [SESSION_COOKIE_AGE](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-SESSION_COOKIE_AGE) setting is, maybe `log.debug` it or something. Perhaps it's something we'd want to add an environment variable for, so we can make sessions for developers last longer.

Also, maybe check the [SESSION_EXPIRE_AT_BROWSER_CLOSE](https://docs.djangoproject.com/en/1.8/ref/settings/#session-expire-at-browser-close) setting. Maybe closing a browser or a tab is killing the session.

**Comment by noisecapella** [comment]
I'm having trouble reproducing it. Whoever reviews this should keep a look out but I feel like the session expiration issue is unrelated

**Comment by noisecapella** [comment]
Just updated the commit to also show elasticsearch queries!

**Comment by ShawnMilo** [comment]
That's cool!

**Comment by noisecapella** [comment]
Any objects to merging this?

**Comment by ShawnMilo** [comment]
If I understand correctly that the toolbar never loads in production (as the setting comment implies), then the code looks good. I haven't tested it locally. I can do it now, unless someone has done it already.

**Comment by noisecapella** [comment]
That's correct, it shouldn't be seen in production. Can you try it out locally? It will require a docker rebuild

**Comment by ShawnMilo** [comment]
Yeah, I was just realizing it's going to cause me to completely rebuild again to work on my Elasticsearch version, but I found `docker save` and `docker load`, so I'm just backing it up and I'll restore it afterwards. :smile:

**Comment by ShawnMilo** [comment]
Yep, runs fine for me locally. And I was able to do other stuff (import course, create, assign, and filter by taxonomies). Good to merge.

**Pull request merged**
