### PR TITLE
rc/0.6.0

### PR DESCRIPTION
**Pull request by pwilkins**
rc/0.6.0
- [x] Modified learningresource panel to include multi select.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Removed export button for empty repositories.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added test for StaticAsset.loader.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added export functionality for learning resources.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added select2-bootstrap-theme bower component.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Added Select2 to the JS libraries.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Created ICheckbox React component.
  [George Schneeloch](gschneel@mit.edu)
- [x] Made XML preview box for a LearningResource should be read only.
  [Amir Qayyum Khan](amir.qayyum.khan@gmail.com)
- [x] Pinned all versions.
  [Carson Gee](x@carsongee.com)
- [x] Avoided hitting the database for the search page.
  [Shawn Milochik](shawn@milochik.com)
- [x] Added field to Vocabulary to define if it can contain multiple terms.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Incremented xbundle version.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added test for ManageTaxonomies.loader.
  [George Schneeloch](gschneel@mit.edu)
- [x] Changed vocabularies listing page to match the design.
  [Ferdi](ferdial@mit.edu)
- [x] Fixed broken links in the footer.
  [Ferdi](ferdial@mit.edu)
- [x] Removed console.error statement.
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixed bug where export checkboxes were not updated in sync with export count.
  [George Schneeloch](gschneel@mit.edu)
- [x] Fix test failures due to pylint dependency chain.
  [Brandon DeRosier](bdero@mit.edu)
- [x] Created StatusBox component to hold messages and errors.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added shopping cart for export.
  [George Schneeloch](gschneel@mit.edu)
- [x] Changed response vocabulary name to match input and avoid key collision.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added docker support for running worker or Web process by environment.
  [Carson Gee](x@carsongee.com)
- [x] Extended tests for manage_taxonomies.jsx file.
  [Amir Qayyum Khan](amir.qayyum.khan@gmail.com)
- [x] Added description path to listing page.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Removed export view which isn&#39;t used anymore.
  [George Schneeloch](gschneel@mit.edu)
- [x] Refactored code for reloading module into a function.
  [George Schneeloch](gschneel@mit.edu)
- [x] Refactored permission check for listing view.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Updated Haystack to 2.4.0 - Removed automatic index update from deployment.
  [Carson Gee](x@carsongee.com)
- [x] Fixed preview link not showing up in list view.
  [George Schneeloch](gschneel@mit.edu)
- [x] Grouped REST tests by common endpoint.
  [George Schneeloch](gschneel@mit.edu)
- [x] Changed vocabulary term indexing from string to integer.
  [Shawn Milochik](shawn@milochik.com)
- [x] Implemented preview link for learning resource panel.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added sorting to search results.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Implemented learning resource panel updating on every panel open.
  [George Schneeloch](gschneel@mit.edu)
- [x] Used different haystack index for tests to prevent conflict with web application.
  [George Schneeloch](gschneel@mit.edu)

### CODE REVIEW

**Comment by amir-qayyum-khan** [comment]
@pwilkins can you remove this 
`[] Extended tests for manage_taxonomies.jsx file. Amir Qayyum Khan`
 from this PR, 
Because i cant test it here, It contains all unit tests for `manage_taxonomies.jsx`

cc @pdpinch

**Comment by bdero** [comment]
@amir-qayyum-khan If it's all unit tests, I would maybe just check if the coverage report for this build (https://coveralls.io/builds/3186919) shows coverage on the lines that your tests verify.

**Comment by amir-qayyum-khan** [comment]
@bdero it is fine. Coverage is equal to what I have on my local machine.

@pdpinch what do you say?

**Comment by noisecapella** [comment]
The export button is not showing up for a particular non-empty repository, I'll need to investigate that bug.

**Comment by noisecapella** [comment]
It may be easiest just to revert that commit and fix it after the release, the commit is only two lines. Thoughts?

**Comment by ShawnMilo** [comment]
Vocabulary term indexing by primary key (integer) instead of slug confirmed. I marked "avoid hitting the database on the search page" complete because it is covered in unit tests and there's nothing to "see" on the CI site.

**Pull request merged**
