### PR TITLE
Added filtering on vocabulary and learning resource type for learning resources

### PR DESCRIPTION
**Pull request by noisecapella**
Required for confirmation dialog for #522

### CODE REVIEW

**Comment by jamiefolsom** [comment]
So this permits the vocabulary editing functionality (in PR #522) to present a dialog if/when the deletion of/editing of a vocabulary will affect any specific learning resources, or any learning resource types. Correct?

**Comment by jamiefolsom** [comment]
@noisecapella ^^

**Comment by noisecapella** [comment]
Yes, any learning resources connecting with the vocabulary being edited and having the resource type which is being removed via the vocabulary edit.

**Comment by jamiefolsom** [comment]
OK, I see the new tests and the new views.py code is shared between the PRs, as you mentioned.

**Comment by jamiefolsom** [comment]
- [x] Functionality works
- [ ] Tests pass

**Comment by jamiefolsom** [comment]
I get a test failure. Appears to be related to my xml_panel test timing out -- is that what your PR from yesterday is intended to remedy?

```
16:53 $ docker-compose run web tox -e js
js installed: wheel==0.24.0
js runtests: PYTHONHASHSEED='163746082'
js runtests: commands[0] | npm install --no-bin-links --prefix /src
npm WARN package.json lore@0.0.0 No repository field.
js runtests: commands[1] | /src/node_modules/jshint/bin/jshint ui/static/ui/js ui/jstests/
js runtests: commands[2] | /src/node_modules/jsxhint/cli.js ui/static/ui/js/**/*.jsx ui/jstests/**/*.jsx --jsx-only
js runtests: commands[3] | /src/node_modules/jscs/bin/jscs ui/static/ui/js ui/jstests/
No code style errors found.
js runtests: commands[4] | /src/node_modules/karma/bin/karma start
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket 95hGRoFssSw-GOwsIrLF with id 12977419
PhantomJS 1.9.8 (Linux 0.0.0) ERROR: 'There is no timestamp for /base/ui/jstests/test-utils.jsx?noext!'

PhantomJS 1.9.8 (Linux 0.0.0) ERROR: 'There is no timestamp for /base/ui/static/ui/js/static_assets.jsx?noext!'

PhantomJS 1.9.8 (Linux 0.0.0): Executed 4 of 72 SUCCESS (0 secs / 0.119 secs)
PhantomJS 1.9.8 (Linux 0.0.0) Test pagination Textarea should be selected FAILED
    Test timed out
        at /src/node_modules/qunitjs/qunit/qunit.js:659

PhantomJS 1.9.8 (Linux 0.0.0): Executed 68 of 72 (1 FAILED) (0 secs / 14.757 secs)
WARN [web-server]: 404: /api/v1/repositories/test/search/?
WARN [web-server]: 404: /api/v1/learning_resource_types/
WARN [web-server]: 404: /api/v1/repositories/test/search/?
PhantomJS 1.9.8 (Linux 0.0.0): Executed 72 of 72 (1 FAILED) (14.797 secs / 14.819 secs)
ERROR: InvocationError: '/src/node_modules/karma/bin/karma start'
_______________________________________________________ summary ________________________________________________________
ERROR:   js: commands failed
✘-1 ~/repos/lore [feature/gs/filter_vocabulary_resource_type|⚑ 12]

```

**Comment by jamiefolsom** [comment]
Assuming that's fixed by your other PR, this is good to merge from my point of view :+1:

**Pull request merged**
