### PR TITLE
Revert PR #718

### PR DESCRIPTION
**Pull request by noisecapella**
Reverts #718

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Hi @noisecapella,

As steps to review this PR, would it make sense to:
1. Pull master, test locally 
2. Pull @ShawnMilo's branch, test;
3. Then pull your branch and test, to confirm I get what I saw in step #1?

Migrations are run if I docker-compose build, correct?

Thanks,

Jamie

**Comment by noisecapella** [comment]
Make sure to check out the latest of this branch, I just repushed.

It should be sufficient to checkout this branch, run `rebuild_index`, refresh the browser and make sure everything still works. Migrations are run if you run `docker-compose up`, `docker-compose build` doesn't do migrations.

**Comment by jamiefolsom** [comment]
OK, so those steps look good to you, but skipping docker-compose build. Presumably, I have to roll forward from a "pre-718" state to a post-718 state, then to a post-738 state for comparison's sake to test that your PR works, right? Just confirming I understand what to test.

**Comment by noisecapella** [comment]
Yes that sounds right. By the way also check that the code covered in this PR matches with the PR being reverted. That PR includes a merge from master which I think should be ignored by `git revert` but it's best to double check

**Comment by jamiefolsom** [comment]
OK, thanks.

**Comment by jamiefolsom** [comment]
So I did have to run docker-compose build upon pulling master (with 718 merged), because there were some other dependencies that I hadn't yet pulled in. After that, it looks like #718 invokes refresh_index the when you run the server, with no further action on my part -- does that sound right?

**Comment by noisecapella** [comment]
The migration just creates the elasticsearch mapping if it doesn't exist. You will still need to run ./manage.py rebuild_index manually.

**Comment by jamiefolsom** [comment]
Here's what I see when I run `rebuild_index`

```
✔ ~/repos/lore [master|⚑ 12]
16:02 $ git checkout -b revert/gs/718_elasticsearch_dsl origin/revert/gs/718_elasticsearch_dsl
Branch revert/gs/718_elasticsearch_dsl set up to track remote branch revert/gs/718_elasticsearch_dsl from origin.
Switched to a new branch 'revert/gs/718_elasticsearch_dsl'
✔ ~/repos/lore [revert/gs/718_elasticsearch_dsl|⚑ 12]
16:03 $ docker-compose run web python manage.py rebuild_index
Starting lore_stats_1...
Starting lore_elastic_1...
Starting lore_redis_1...
Starting lore_db_1...

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
Failed to clear Elasticsearch index: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f4fc7f045d0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f4fc7f045d0>: Failed to establish a new connection: [Errno 111] Connection refused)
All documents removed.
Indexing 1983 learning resources
No handlers could be found for logger "elasticsearch.trace"
```

Running servers now.

**Comment by jamiefolsom** [comment]
Branch checked out.
- [x] Functionality looks good
- [x] No console errors
- [ ] Code looks good
- [ ] Tests pass

**Comment by noisecapella** [comment]
I think that chunking the resources may work to avoid the memory problem, it's my last commit in #739. I'm going to wait until Monday before making sure. Can you hold on merging?

**Comment by jamiefolsom** [comment]
Definitely, I was not going to merge at this point; I still have to compare this PR and #718. Have a nice weekend!

**Comment by noisecapella** [comment]
I'm going to close this since I believe we're going to submit a separate PR to fix the issue rather than revert it

**Pull request closed without merging**
