### PR TITLE
rc/0.12.0

### PR DESCRIPTION
**Pull request by pwilkins**
Release 0.12.0
- [x] Added task to index resources via Celery.
  [George Schneeloch](gschneel@mit.edu)
- [x] Wrapped course imports in transaction
  [George Schneeloch](gschneel@mit.edu)
- [x] Limited vocabularies to repository being searched
  [George Schneeloch](gschneel@mit.edu)
- [x] Removed haystack
  [George Schneeloch](gschneel@mit.edu)
- [x] Updated Django to 1.8.5 due to a bugfix release.
  [Shawn Milochik](shawn@milochik.com)
- [x] Wrapped description text to 2 lines and added expand collapse description functionality
  [Amir Qayyum Khan](amir.qayyum.khan@gmail.com)
- [x] Moved Pagination inside Listing React component
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixed reindexing for edited vocabularies
  [George Schneeloch](gschneel@mit.edu)
- [x] Updated status tests to use settings context
  [George Schneeloch](gschneel@mit.edu)
- [x] Added limit to memory for Docker
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixed resource ids
  [George Schneeloch](gschneel@mit.edu)
- [x] Chunked bulk indexing to lower memory footprint
  [George Schneeloch](gschneel@mit.edu)
- [x] Added debug_toolbar
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixed mouse pointer on edit and delete links
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixing memory usage in transaction
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Fixed collapse behavior
  [George Schneeloch](gschneel@mit.edu)
- [x] Fixed newrelic not reporting
  [Brandon DeRosier](x@bdero.me)
- [x] Changed get_or_create to create
  [George Schneeloch](gschneel@mit.edu)
- [x] Replace Haystack queryset and facet counts with elasticsearch-dsl.
  [Shawn Milochik](shawn@milochik.com)
- [x] Fixed id attribute for vocab and term select
  [George Schneeloch](gschneel@mit.edu)
- [x] Added filtering on vocabulary and learning resource type for learning resources
  [George Schneeloch](gschneel@mit.edu)
- [x] Configured newrelic python agent
  [Brandon DeRosier](x@bdero.me)
- [x] Implemented verification of resource types on models
  [George Schneeloch](gschneel@mit.edu)
- [x] Static assets are served again using local storage
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Fixed missing test module
  [George Schneeloch](gschneel@mit.edu)
- [x] Replaced default missing title and updated description path
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Pinned PyTest to a version < 2.8
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Added bulk insert of static assets during import.
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Added loader to listing, resource panel and taxonomy panel.
  [George Schneeloch](gschneel@mit.edu)
- [x] Added vocabulary editing in the taxonomy panel.
  [Amir Qayyum Khan](amir.qayyum.khan@gmail.com)
- [x] Added documentation for LORE release workflow
  [pwilkins](pwilkins@mit.edu)

### CODE REVIEW

**Comment by noisecapella** [comment]
I think we're missing a checkbox for "Bulk insert of static assets during import" #705

**Comment by noisecapella** [comment]
Also 'Added loader to listing' #750

**Comment by ShawnMilo** [comment]
@bdero: Human ssh request for Django version checkbox.

```
In [1]: import django
In [2]: print django.VERSION
(1, 8, 5, 'final', 0)
```

**Comment by ShawnMilo** [comment]
@bdero: Human ssh request to show Haystack is no longer being used:

``` sh
grep SearchQuerySet search/api.py
```

There's a lingering comment mentioning the `SearchQuerySet`, but there should be no import or other code.

**Comment by noisecapella** [comment]
#522 should also be in this release notes

**Pull request merged**
