### PR TITLE
Add logging, especially for use during development and testing.

### PR DESCRIPTION
**Pull request by ShawnMilo**
Logging config.

### CODE REVIEW

**Comment by carsongee** [comment]
I actually don't want to log to a file, or at least if we are going to log to a file, we should also log to stdout/stderr for it to be a 12 factor app.  I would also like the log level to be configurable with an environment variable that defaults to `DEBUG`.  While we are here, it would also be nice to configure it to log to syslog.  As a specific example, our [flask logging extension](https://github.com/mitodl/flask-log/blob/master/flask_log.py) has some pointers on how to set things up, though it will be different in Django

**Comment by carsongee** [comment]
Also, you have set here to disable existing loggers, but we still need the uncaught exception logger to be there so that we get e-mails on uncaught exceptions i.e.

``` python
...
        'filters': {
...
            'require_debug_false': {
                '()': 'django.utils.log.RequireDebugFalse',
            }
        },
...
        'handlers': {
...
            'mail_admins': {
                'level': 'ERROR',
                'filters': ['require_debug_false'],
                'class': 'django.utils.log.AdminEmailHandler'
            },
...
        'loggers': {
...
            'django.request': {
                'handlers': ['mail_admins'],
                'level': 'ERROR',
                'propagate': True,
            },
```

**Comment by ShawnMilo** [comment]
My main goal was to having logging I can see when running tests. When I use a standard logging setup it doesn't show anywhere on the screen. If you know a way I can log during tests (even if it's on stdout -- I don't need a file either), I'd be happy to adopt that method.

**Comment by carsongee** [comment]
I can go ahead and do this sometime soon, for the short term, you might try installing https://pypi.python.org/pypi/pytest-capturelog as it will spit out captured logging like nose does I think.  If that works, maybe drop a small PR for that, and we can hold off on the more sensitive logging situation to work for testing and production.

**Comment by ShawnMilo** [comment]
This should be closed because it seems like we want to take an alternate approach.

**Pull request closed without merging**
