### PR TITLE
Fixed counter in learning resouce exports panels header

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
Hi,

In this PR i made Learning resources select counter in Exports panel header consistent with the resources select in listing.

issue https://github.com/mitodl/lore/issues/471
https://github.com/mitodl/lore/pull/474
@pdpinch @noisecapella 

screen shot 2015-08-11 at 7 54 54 pm

screen shot 2015-08-11 at 7 54 05 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
Note that this is a PR to refactor/gs/listing_resource_jsx

**Comment by pdpinch** [comment]
@amir-qayyum-khan please rebase when you have a chance --  @noisecapella has been doing a lot of work on refactor/gs/listing_resource_jsx

**Comment by amir-qayyum-khan** [comment]
Done @noisecapella 
cc @pdpinch

**Comment by jamiefolsom** [comment]
@amir-qayyum-khan and @noisecapella, a question on process: when there are conflicts, and/or a lack of passing checks on a PR, should those generally be resolved before review? Both are the case here. Thanks!

**Comment by jamiefolsom** [comment]
- [x] js tests pass
- [x] no errors in the browser console
- [ ] functionality works as expected
- [x] code style is good
- [x] code clarity is good
- [ ] UX is intuitive, and consistent with the rest of the application.

**Comment by jamiefolsom** [comment]
Hi @amir-qayyum-khan. When you click the export button to open the side panel, then uncheck the resources, then click the "X" button at top right to close the panel, the count remains the same in the side panel and in the main page, and the resources remain selected in the main page. In other words, those checkboxes don't do anything, that I can tell.

First screenshot shows four unchecked resources, with the count still at 4. 

screenshot 2015-09-01 15 19 26

Second screenshot shows list after unchecking 4 LRs in panel, and closing it. Note count still at 4, and resources still selected in list.

screenshot 2015-09-01 15 27 05

Side issue; when I export with some resources checked, some unchecked in the side panel, I get a number of resources in the downloaded zipfile which doesn't correspond to the number of resources checked, either in the main page or in the side panel.

cc @noisecapella

**Comment by noisecapella** [comment]
It's generally best to fix the tests and rebase before a review since it will necessary involve extra code to review, but sometimes this happens during a review and you just have to review those changes again.

**Comment by noisecapella** [comment]
Regarding the export links behavior, that's fixed in master

**Comment by jamiefolsom** [comment]
Upon download, the browser console contains a message: `react-with-addons.js:1534: Resource interpreted as Document but transferred with MIME type application/x-tar: "http://192.168.59.103:8070/media/resource_exports/mitodl_exports.tar.gz"`. Presumably, this can be ignored, as it is neither an error nor a warning. Also, while related, it's not in scope for this PR.

**Comment by jamiefolsom** [comment]
@noisecapella re: export -- thx.

**Comment by jamiefolsom** [comment]
OK, reviewed to the extent possible pending a rebase. @amir-qayyum-khan @noisecapella. Unchecked issues [above](https://github.com/mitodl/lore/pull/496#issuecomment-136832050) are the ones that stood out.

**Comment by jamiefolsom** [comment]
I see 404s on two images in the console output when running `docker-compose run web tox -e js`:

```
WARN [web-server]: 404: /images/ic-pieces.png
WARN [web-server]: 404: /images/ic-book.png
```

**Comment by noisecapella** [comment]
Unfortunately we can't do anything about those 404's at the moment. We only mock AJAX calls and those aren't AJAX. Possibly karma has some way of letting us fake those URLs or at least ignore those errors.

**Comment by noisecapella** [comment]
Closing since we've merged the PR already. I'll make a separate PR with this code against master

**Pull request closed without merging**
