### PR TITLE
Implemented Select2 React class

### LINKED ISSUE #459: Create Select2 React component
This will take the work done by @giocalitri and make it into a reusable component

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #459

### CODE REVIEW

**Comment by jamiefolsom** [comment]
UI functionality works for me. Coverage is unchanged. @carsongee want to have a look at the code? Looks good to me, but would be good to have your opinion. Thx!

**Comment by carsongee** [comment]
It appears that scrolling the panel doesn't work, though I don't know what is causing it.

**Comment by noisecapella** [comment]
Ok, the scrolling issue seems to be fixed now

**Comment by carsongee** [comment]
I Verified that scrolling works as expected

**Pull request merged**
