### PR TITLE
Reformatted CSS

### PR DESCRIPTION
**Pull request by noisecapella**
Just whitespace changes

### CODE REVIEW

**Comment by ShawnMilo** [comment]
I've confirmed it's whitespace only. Good to merge after tests pass.

**Comment by noisecapella** [comment]
Seems to have failed due to a timeout, can someone repush and run it again?

**Comment by ShawnMilo** [comment]
Sure. I'll do that, and merge if it's successful.

**Comment by ShawnMilo** [comment]
Running here. Will follow up. https://travis-ci.org/mitodl/lore/builds/74613023

**Pull request merged**
