### PR TITLE
Added calls to get_conn() where conn is used implicitly.

### PR DESCRIPTION
**Pull request by ShawnMilo**
Quick fix made. I just pushed it up for review, but I haven't added any tests yet. If it fixes the issue in CI and we're under a time crunch for a release, I'll add the tests in another branch.

No test excuses: 
- Two hour meeting in five minutes.
- Wanted a fix ASAP because the bug is in CI.

### CODE REVIEW

**Comment by ShawnMilo** [comment]
Fixes #689

**Comment by noisecapella** [comment]
Looks good to me

**Comment by giocalitri** [comment]
:+1:

**Comment by noisecapella** [comment]
Can you file another issue to handle the tests for this issue?

**Comment by ShawnMilo** [comment]
@noisecapella: Done, see #691.

**Pull request merged**
