### PR TITLE
Disable SSL validation for a test which uses urltools

### PR DESCRIPTION
**Pull request by bdero**
This is currently a common problem with python >= 2.7.9:
http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error
https://github.com/servo/servo/issues/5917

### CODE REVIEW

**Comment by noisecapella** [comment]
:+1:

**Comment by bdero** [comment]
The tests should let us know if it works

**Comment by giocalitri** [comment]
:+1:

**Comment by noisecapella** [comment]
The build is reporting some PEP8 failures:

```
__________________________________ PEP8-check __________________________________
/home/travis/build/mitodl/lore/tests/test_urls.py:11:80: E501 line too long (102 > 79 characters)

ssl._create_default_https_context = ssl._create_unverified_context  # pylint: disable=protected-access

                                                                               ^

/home/travis/build/mitodl/lore/tests/test_urls.py:12:1: E402 module level import not at top of file

from urltools import compare

^
```

**Comment by giocalitri** [comment]
Yeah.... you need to put the pylint disable before line 11 and not next to it

**Comment by bdero** [comment]
If I were to put the pylint disable above it, that would disable the failure for the file rather than the single line.

**Comment by bdero** [comment]
The coverage changes other than the 1 line which is covered in python 2 from my change is unrelated to this change. Merging this.

**Pull request merged**
