### PR TITLE
make repository name a link

### PR DESCRIPTION
**Pull request by Ferdi**
#90

### CODE REVIEW

**Comment by Ferdi** [comment]
mitelorehomenew

**Comment by pdpinch** [comment]
There's a test that depends on this template. We'll need to change https://github.com/mitodl/lore/blob/1eb5d12a62f98b2cd6162e1f9c44cd5753d9f2f4/learningresources/tests/test_views.py#L42

**Comment by Ferdi** [comment]
Shawn,  can you look pls?
- Sent from my phone

**Comment by ShawnMilo** [comment]
Yes, it'll need a trivial change. I'll see if I can add a quick patch.

**Comment by ShawnMilo** [comment]
Yes, there's an easy fix for that. Delete the line Peter linked to, and the comment above it, since they're deprecated now. They're testing for a redirect to the Welcome page, which has been removed.

**Comment by Ferdi** [comment]
Can you fix please?
- Sent from my phone

**Comment by ShawnMilo** [comment]
Done.

**Comment by pdpinch** [comment]
Again with the 0.0%. I'll merge anyway.

**Pull request merged**
