### PR TITLE
Pinned PyTest to a version < 2.8

### PR DESCRIPTION
**Pull request by giocalitri**
pytest-capturelog has problems with the latest version and
raises warnings

### CODE REVIEW

**Comment by noisecapella** [comment]
What do the warnings look like? Would they show up in travis logs?

**Comment by giocalitri** [comment]
no, they do not show up anywhere because the `pytest-capturelog` uses a deprecated function

**Comment by giocalitri** [comment]
BTW: this is the issue 
https://github.com/eisensheng/pytest-catchlog/issues/3

**Comment by noisecapella** [comment]
Sounds good, feel free to merge

**Pull request merged**
