### PR TITLE
Added learning resource UI to edit description and terms

### PR DESCRIPTION
**Pull request by noisecapella**

### CODE REVIEW

**Comment by pwilkins** [comment]
@noisecapella Please confirm that this PR addresses issue #298 "Apply terms to learning resources"
It appears that @giocalitri is the assignee in Pivotal https://www.pivotaltracker.com/story/show/98360884 and I'd like to correct that if it's an error.

**Comment by giocalitri** [comment]
I know it is still work in progress, but I just noticed a couple of things:
1- the confirmation message when you submit the form has no background
2- the textarea width is not consistent
3- Probably unrelated to this issue, the XML texture is too tall (compared with the [UI design](http://pureui.com/c/mit/lore/build001/))
learning_resource

**Comment by giocalitri** [comment]
@pwilkins No it does not: this part is to edit the description

**Comment by noisecapella** [comment]
To clarify, this covers both editing terms and the description

**Pull request merged**
