### PR TITLE
rc/0.13.0

### PR DESCRIPTION
**Pull request by pwilkins**
Release v0.13.0
- Refactored listing code for testing
- Implemented lazy loading for resource tab
- Added custom slugify function to allow any name for Repo, Vocab, Term
- Fixed index mapping of terms and vocabularies
- Set Elasticsearch log level higher during testing
- Set Spinner zIndex to 0 to not have it float above everything else
- Added loader on save
- Removed unused functions
- Fixed link click behavior for term edit and delete

### CODE REVIEW

**Comment by ShawnMilo** [comment]
It's nice that George let Giovanni help a little. ^_^

**Comment by giocalitri** [comment]
How is it possible that we have merge conflicts?
The code seems to go from 0.11 to 0.13 directly...

**Comment by bdero** [comment]
@pwilkins The problem with this release is that something's not quite right about the last release (https://github.com/mitodl/lore/pull/780).

Notice that there is currently a different number of commits between the release branch and the release-candidate.
https://github.com/mitodl/lore/tree/release
https://github.com/mitodl/lore/tree/release-candidate

**Comment by bdero** [comment]
In the release branch PR, there are 32 commit descriptions listed, and 103 commits listed for the merge: https://github.com/mitodl/lore/pull/781 
In the release-candidate PR, there are 27 commit descriptions listed, and 14 commits listed for the merge: https://github.com/mitodl/lore/pull/780

The difference in the number of commit descriptions is 5, which is the same as the number of commits in the commit histories of each branch, so this is where the discrepancy is. There are 5 commits that made it to the release, but not the release candidate. Figuring out which ones they were.

**Comment by bdero** [comment]
Actually, it looks like they're evened out, and the difference is just a different number of single-parent merge commits.

After staring at this for a bit, I think I understand what's going on here now -

Look at the bottom of both of these:
https://github.com/mitodl/lore/pull/780/commits
https://github.com/mitodl/lore/pull/781/commits

Notice that the tip of rc/0.12.0 was different between the time of merging. The release candidate has this 0.12.0 notes version: https://github.com/mitodl/lore/commit/8eed1bd21159789212746b4eae99dd4efd53b422 and the release has this version: https://github.com/mitodl/lore/commit/2e94636d9d27059fbe60d57f0606d7d72e751030

After the release, the `release` branch was merged into `master`, so master got the https://github.com/mitodl/lore/commit/2e94636d9d27059fbe60d57f0606d7d72e751030 version of the commit. This is why we have conflicts.

@pwilkins To fix this, we can reset the release-candidate branch to be at the release notes version currently in `release` and `master`: https://github.com/mitodl/lore/commit/2e94636d9d27059fbe60d57f0606d7d72e751030

**Comment by bdero** [comment]
@pwilkins All it should take is:

```
git checkout release-candidate
git reset --hard 2e94636d9d27059fbe60d57f0606d7d72e751030
git push --force origin release-candidate
```

Be careful that your local repository isn't in conflict resolution mode from an earlier merge you were trying, though. If it is, you can do `git merge --abort` to get out of it.

**Pull request merged**
