### PR TITLE
The export URL includes the repository

### PR DESCRIPTION
**Pull request by giocalitri**
This PR is strictly dependent on Shawn PR #173 and should be reviewed and merged only after that one.

The changes here are minimal.

### CODE REVIEW

**Comment by ShawnMilo** [comment]
The review looks fine, but I'd like to have another look after #173 is merged, because there's a lot of noise here from that branch.

**Comment by giocalitri** [comment]
I totally agree.

**Comment by ShawnMilo** [comment]
This has two commits, and also still shows the changes from #173. Please rebase from `master`.

Thanks.

**Comment by giocalitri** [comment]
wait

**Comment by ShawnMilo** [comment]
Reviewed, will push after Travis passes.

**Pull request merged**
