### PR TITLE
Rc/0.8.0

### LINKED ISSUE #312: Static (django) assets aren't precompiled in production
Whenever heroku changes our dynos out, we lose a very slow request to compiling assets (jsx/JavasSript/CSS).  We should precompile these with `collectstatic` and possibly even serve them from s3.

### LINKED ISSUE #431: Install statsd and instrument code base
Thoughts on things to be instrumented:
- Time to import
- Time to update index per hook
- Time to pull search on listing page

### LINKED ISSUE #509: Add Google Analytics

### PR DESCRIPTION
**Pull request by pdpinch**
Release candidate 0.8.0
- [x] Changed how vocabulary terms are applied to Learning Resources to use two dropdowns instead of a growing list of fields.
  [Jamie Folsom](jamiefolsom@gmail.com)
- [x] Added deployment for release candidates
  [Carson Gee](x@carsongee.com)
- [x] Added deploy button and app.json
  [Carson Gee](x@carsongee.com)
- [x] Fixed caching bug.
  [Shawn Milochik](shawn@milochik.com)
- [x] Fixed panel shade issue
  [George Schneeloch](gschneel@mit.edu)
- [x] Added base sorting field in case used sorting is working on same values
  [Giovanni Di Milia](gdimilia@mit.edu)
- [x] Removed response from PATCH on learning resource to aid in performance
  [George Schneeloch](gschneel@mit.edu)
- [x] Added configuration option and heroku command to pre-compress assets Closes #312
  [Carson Gee](x@carsongee.com)
- [x] Added Google Analytics tracking support Closes #509
  [Carson Gee](x@carsongee.com)
- [x] Reduce workers per dyno to avoid memory issues
  [Carson Gee](x@carsongee.com)
- [x] Added statsd and a few timers - Import timer - Index signal handler timers - Search page load time Closes #431
  [Carson Gee](x@carsongee.com)
- [x] Updated indexing caching from dict to Django's cache.
  [Shawn Milochik](shawn@milochik.com)
- [x] .tile-meta no longer defined twice
  [tejsheth](tejsheth@mit.edu)
- [x] Split builds and removed python 3.3 testing
  [Carson Gee](x@carsongee.com)
- [x] revert tile-meta and meta-item for previous appearance
  [tejsheth](tejsheth@mit.edu)
- [x] Adds import for (sample) xanalytics API data.
  [Shawn Milochik](shawn@milochik.com)
- [x] Added closing panels with ESC key
  [Amir Qayyum Khan](amir.qayyum.khan@gmail.com)
- [x] Fixed export button to show up even without search results.
  [George Schneeloch](gschneel@mit.edu)
- [x] Updated CSS and HTML according to mockup changes
  [George Schneeloch](gschneel@mit.edu)
- [x] Added xanalytics icons to listing page
  [George Schneeloch](gschneel@mit.edu)
- [x] Added xanalytics management command.
  [Shawn Milochik](shawn@milochik.com)

### CODE REVIEW

**Comment by ShawnMilo** [comment]
"Updated indexing caching from dict to Django's cache." and "Fixed caching bug" are implicitly known to be there by the code being merged in, so I clicked the checkbox for each.

**Comment by ShawnMilo** [comment]
@carsongee request: Please confirm presence of "Added xanalytics management command" at the command line via "human ssh."

**Comment by ShawnMilo** [comment]
To which branch/commit does "Adds import for (sample) xanalytics API data" refer? If this is the "dormant" code (sleeping until the API is created and we populate the `XANALYTICS_URL` environment variable, then this can not be tested in the CI environment.

**Comment by ShawnMilo** [comment]
@bdero: [please see this](https://github.com/mitodl/lore/pull/543#issuecomment-132605250)

**Comment by pdpinch** [comment]
https://github.com/mitodl/lore/pull/403

# 

> "Adds import for (sample) xanalytics API data"

**Comment by ShawnMilo** [comment]
Thanks, @pdpinch. I clicked the checkbox, since this _is_ [the functionality](https://github.com/mitodl/lore/pull/543#issuecomment-132605698) I suspected.

**Comment by carsongee** [comment]
I've run the management command and populated analytics

**Comment by ShawnMilo** [comment]
Thanks, @carsongee. @pdpinch, my last item is checked off.

**Pull request merged**
