### PR TITLE
Fixed link click behavior for term edit and delete

### LINKED ISSUE #784: Edit and delete term links don't call event.preventDefault()

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #784

### CODE REVIEW

**Comment by giocalitri** [comment]
I think this is good as is: do I need to check functionality?

**Comment by noisecapella** [comment]
It would be good to check functionality just to make sure this does what it seems to, and it should be a quick check. You should be able to click the edit and delete term icons without a '#' showing up in the URL

**Comment by giocalitri** [comment]
will do now

**Comment by giocalitri** [comment]
Functionality is fine: feel free to merge

**Comment by noisecapella** [comment]
Thanks for your diligence :)

**Pull request merged**
