### PR TITLE
Configured newrelic python agent

### PR DESCRIPTION
**Pull request by bdero**
As we talked about it a little bit in our sprint retrospective, I've configured `lore-ci` to use the free newrelic service so we can try it out. For the free service, there is no dyno/time limit, but transactions aren't measured: https://addons.heroku.com/newrelic#wayne

It's easy to switch to a paid plan in the future if we needed, though.

### CODE REVIEW

**Comment by bdero** [comment]
If this PR is merged, newrelic should also be turned on in `lore-rc` and `lore-release`.

**Comment by bdero** [comment]
Restarted the PR build - one test failed due to a network-related issue:

```
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=10)
```

**Comment by pdpinch** [comment]
Where would we see the reporting from this?

FYI @Ferdi

**Comment by bdero** [comment]
Collaborators can access newrelic from the heroku app view.

**Comment by ShawnMilo** [comment]
And by logging into newrelic.com, right?

**Comment by bdero** [comment]
That's where you view all of the stats, but it's a single-sign on from heroku's app dashboard. There is an email confirmation we got for [somehash]@heroku.com, but I'm not sure if it's possible to login directly from newrelic.com. Maybe a password can be set.

**Comment by bdero** [comment]
@ShawnMilo Actually, it looks like we can invite each member via email and that will enable us to login directly.

**Comment by bdero** [comment]
FYI, This is the config guide I followed: https://docs.newrelic.com/docs/agents/python-agent/getting-started/django-heroku-quick-start

Let's merge this today or tomorrow so we can verify this works correctly on lore-ci, and then configure lore-rc and lore-release in preparation for the next release (because I will be out next week).

**Comment by pdpinch** [comment]
I don't know how this magic works, but you seem to have followed the recipe. :+1:

**Pull request merged**
