### PR TITLE
fix redirect issue on list of repository.html page

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
Hi

In this PR I fixed issue when user is not login and try to access repository.html then currently app is showing exception instead of redirecting to login page.

I fix it by redirecting to login page if user is not login

https://github.com/mitodl/lore/issues/223
cc @pdpinch @ShawnMilo @carsongee

### CODE REVIEW

**Comment by carsongee** [comment]
This fixes only a very narrow use case.  I was hoping we could do this more widespread, i.e. have it work for all views, since the XML detail view for example, has the same behavior.  There are probably just a couple more spots than this

**Comment by carsongee** [comment]
This will also need a test to validate the new behavior

**Comment by carsongee** [comment]
You should really just add the `@login_required` decorator to these views as it will handle all of that.  We don't want to redirect them to login if they already are logged in but don't have permissions as that would cause a redirect loop.

**Comment by amir-qayyum-khan** [comment]
@carsongee if I use `@login_required on __call__` it gives me exception https://gist.github.com/amir-qayyum-khan/57c407522ffaf6b905fb

If I try to add `@login_required on top of class RepositoryView(FacetedSearchView):` i get exception https://gist.github.com/amir-qayyum-khan/8377ed82602b6cdda0fc

@carsongee what If I check if user is in logged in and instead of redirecting him to login page i can redirect him to listing page in case where user has no permission. To avoid any redirect loop.

cc @pdpinch

**Comment by carsongee** [comment]
Have you tried: http://stackoverflow.com/questions/14694754/haystack-login-required ?

**Comment by amir-qayyum-khan** [comment]
Done @carsongee

**Comment by amir-qayyum-khan** [comment]
test this please

**Comment by amir-qayyum-khan** [comment]
please test this

**Comment by carsongee** [comment]
Can you add this to all of these views?  For the other ones, you should be able to just use the regular login_required decorator

**Comment by amir-qayyum-khan** [comment]
@carsongee as we discuss login_required is present all over the ui/view and i just remove one use less decorator from `RepositoryView.dispatch`, and test

**Pull request merged**
