### PR TITLE
Reduce logging level of elasticsearch and urllib3

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by ShawnMilo** [comment]
Looks good; will merge once Travis is done with it.

**Comment by bdero** [comment]
@ShawnMilo He's going to try changing the log level to info to see if that's alright

**Comment by ShawnMilo** [comment]
So hold off on merging even if it passes?

**Comment by bdero** [comment]
Nah, it should be good to merge after it passes. I forgot that the build takes forever and there was therefore no chance of it finishing before it was updated again. ;)

**Pull request merged**
