### PR TITLE
Cleared message box on changes to the learning resource panel

### LINKED ISSUE #609: Remove save confirmation when learning resource panel is updated
As a curator, I find it confusing when I:
1. make a change
2. save my change
3. make another change, and
the save confirmation message is still in the same location? Was my change saved?

The confirmation messages should be removed when more changes are made to the learning resource panel.

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #609

### CODE REVIEW

**Comment by pdpinch** [comment]
functionality is good. 

no tests? It's ok, but I wanted to check.

**Comment by noisecapella** [comment]
That's an oversight, I'll add a test

**Comment by noisecapella** [comment]
Ok, test is in place

**Comment by giocalitri** [comment]
~~I just verified that this PR introduced the bug #725~~

**Comment by giocalitri** [comment]
I take it back: the weird behavior of #725 is caused by the `firebug` plugin.

This PR can be merged

**Pull request merged**
