### PR TITLE
Updated apiary docs for recent changes to API

### LINKED ISSUE #394: Update apiary docs for various changes we made
In these PRs we forgot to update apiary with the PR. We can do it all at once in a separate PR:
- #294
- #263  
- #333
- #341 (name field)

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #394

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Hi @noisecapella, these API docs get published at http://lore.odl.mit.edu/api/v1/repositories/, eg, correct?

**Comment by noisecapella** [comment]
No, they are hosted at http://docs.lore.apiary.io/. The Django REST framework schema information is generated from the serializers provided in the Python code.

**Comment by jamiefolsom** [comment]
Ah, ok. Thanks.

**Comment by noisecapella** [comment]
To view these changes in a rendered format you can download the [apiary gem](https://github.com/apiaryio/apiary-client) and run `apiary preview` inside the LORE directory.

**Comment by jamiefolsom** [comment]
Gotcha. And is there/should there be a link somewhere to that resource? I'd seen it, but only because someone verbally mentioned it to me in person (probably you). If we want anyone to find these, we might point to them if we're not already. Is there a website for prospective LORE users, devs, integrators, for example? Just curious.

**Comment by noisecapella** [comment]
Actually there is an issue for that #250 :)

**Comment by jamiefolsom** [comment]
Aha. Maybe I'll knock that one off. Thanks!

**Comment by noisecapella** [comment]
Is this still under review?

**Comment by pdpinch** [comment]
LGTM :+1:

**Pull request merged**
