### PR TITLE
Replaced the status app with django-server-status

### LINKED ISSUE #889: Integrate django-server-status
We have mitodl/django-server-status now which usurps the status app in this repo. We should port to that, which should be pretty effortless.

### PR DESCRIPTION
**Pull request by giocalitri**
#### What are the relevant tickets?

fixes #889 
#### What's this PR do?

replaces the built in status app with the `django-server-status` library
#### Where should the reviewer start?

`settings.py`
#### How should this be manually tested?

rebuild the container and check that the new response from the status contain the keys `celery` and `status_all`

### CODE REVIEW

**Comment by noisecapella** [comment]
This generally looks good, although the celery portion of the app isn't working because there's no `USE_CELERY` setting defined. Is that a blocker?

**Comment by giocalitri** [comment]
This generally looks good, although the celery portion of the app isn't working because there's no USE_CELERY setting defined. Is that a blocker?

Probably it is: I will look into it.

**Comment by giocalitri** [comment]
@noisecapella: Now everything works.

@pdpinch this needs attention before releasing to production to check if everything works fine for the imports and everything that uses `celery` in general.

**Comment by noisecapella** [comment]
Looks good now :+1:

**Pull request merged**
