### PR TITLE
Open edX Conference demo release

### PR DESCRIPTION
**Pull request by pwilkins**
Release for use at Open edX Conference demo.

### CODE REVIEW

**Comment by pdpinch** [comment]
something weird going on with the comments here... 

The release notes are going to need a lot of scrubbing....

**Comment by pwilkins** [comment]
I thought the sole purpose of this release was to provide a "safe" place for Ferdi to demo.

**Comment by pdpinch** [comment]
It is, but someday there will be release notes and they will require a lot of scrubbing

**Comment by noisecapella** [comment]
We forgot to squash the haystack -> elasticsearch PR, that's why there are the comments there.

**Pull request merged**
