### PR TITLE
Added form for adding new vocabularies.

### LINKED ISSUE #122: Add manage taxonomies slide drawer to repository page
See http://pureui.com/c/mit/lore/build001/

The Taxonomies tab should use a REST call to get a list of vocabularies and their possible values (when available) (this probably needs it's own story with more detail)

The add vocabulary tab should display the form currently at https://lore-ci.herokuapp.com/repositories/another-repo/vocabularies/vocab1/ (this probably needs another story)

### PR DESCRIPTION
**Pull request by carsongee**
Closes #122
[finished #98029112]

### CODE REVIEW

**Comment by carsongee** [comment]
Demo vid at https://www.youtube.com/watch?v=zLqn3c91glo&feature=youtu.be once it is done processing

**Comment by pwilkins** [comment]
I clicked the plus sign on an empty Term textbox and I got an error message that doesn't go away, even after adding a new term.

screen shot 2015-07-01 at 3 00 29 pm

**Comment by carsongee** [comment]
That is out of scope for this PR since that came in with #248 , but @noisecapella is working on it now I think.

**Comment by pwilkins** [comment]
The issue with the error message I identified is fixed by PR #280

**Pull request merged**
