### PR TITLE
Removed ? from URL if empty query

### LINKED ISSUE #681: Remove '?' from URL if query string is empty
It's mostly just a pet peeve but it could complicate testing where URLs need to be exact

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #681

### CODE REVIEW

**Comment by giocalitri** [comment]
Looks good. No tests? (just asking)

It can be merged if tests are not necessary

**Comment by noisecapella** [comment]
We do have test_listing.js now, I'll see what I can do

**Comment by noisecapella** [comment]
Ok, there is a test now and some extra work to fix missing mocks for test_listing.js

**Comment by giocalitri** [comment]
Looks good to me

**Pull request merged**
