### PR TITLE
Added xanalytics management command.

### PR DESCRIPTION
**Pull request by ShawnMilo**
Populate  xanalytics data from the command line with
random data.

This is as stand-alone extraction of the management command merged into #166 as #472.

### CODE REVIEW

**Comment by carsongee** [comment]
I'm not seeing the management command here

**Comment by ShawnMilo** [comment]
@carsongee: FYI. I tested the app locally; if the full suite passes on Travis this should be "mergeable" into master.

**Comment by ShawnMilo** [comment]
It's here:

`xanalytics/management/commands/populate_xanalytics.py`

This is how the [current docs](https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/) describe it.

**Comment by carsongee** [comment]
Cool, looks good, assuming tests pass, maybe we can get this post code freeze so I don't have to do it on the side. What do you think @pwilkins?

**Comment by carsongee** [comment]
When I had looked the diff only had 2 files in it for whatever reason, and did not have the management command.

**Comment by ShawnMilo** [comment]
Yeah, I failed to `git add` some files at first after applying a patch locally.

**Pull request merged**
