### PR TITLE
Added React component for not tagged counts

### LINKED ISSUE #617: UI for missing facet
- [ ] Add a "not tagged" items to the list of terms in the facet. This term should be styled differently, but we haven't determined what that will be yet. 
- [ ] Clicking the number should perform a query that returns a set of the learning resources with no value for that field. Otherwise, the query should behave the same as any other facet. The facet label will need to remain visible, unlike it does currently.

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #617

### CODE REVIEW

**Comment by giocalitri** [comment]
The only thing I see missing are tests.

**Comment by noisecapella** [comment]
Tests should be there now

**Comment by giocalitri** [comment]
Is this PR dependent in any way to #614 ?

**Comment by noisecapella** [comment]
No, they are independent. Currently we have no tests for listing.js at all, that PR adds it to code coverage and a couple trivial tests

**Comment by giocalitri** [comment]
Ok, just to be sure of the review sequence.

**Comment by giocalitri** [comment]
Code looks fine.
Checking functionality

**Comment by giocalitri** [comment]
This can be merged

**Comment by noisecapella** [comment]
I'll add tests to verify that the facet doesn't show up if count is empty

**Comment by giocalitri** [comment]
:+1:

**Comment by giocalitri** [comment]
The new test looks fine.
Merge as soon as tests pass

**Pull request merged**
