### PR TITLE
Added listing refresh after taxonomy changes

### LINKED ISSUE #641: Refresh listing after updating taxonomy
Currently the user needs to refresh the listing to see the new vocabularies. This matters more now with the addition of 'not tagged'. The implementation should take a callback which asks to refresh the listing similar to how the learning resource panel does it

### PR DESCRIPTION
**Pull request by noisecapella**
Fixes #641

### CODE REVIEW

**Comment by giocalitri** [comment]
There is a problem with a test.

**Comment by giocalitri** [comment]
I checked the code and looks fine: maybe add a test to check that the `refreshFromAPI` gets called

**Comment by noisecapella** [comment]
The problem seems to be that I didn't update the tests to pass a callback for `refreshFromAPI`

**Comment by giocalitri** [comment]
Well, that addresses also my comment

**Comment by giocalitri** [comment]
I guess it does not, actually

**Comment by noisecapella** [comment]
refreshFromAPI calls should now be asserted

**Comment by giocalitri** [comment]
Code looks good: checking functionality

**Comment by giocalitri** [comment]
Functionality looks good as well
it can be merged as soon as tests pass

**Pull request merged**
