### PR TITLE
Made better navigation of paging in search results

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
In this PR I added
- Current page and max page information to pagination widget
- On Clicking widget a text field appears. User can enter any page number greater the 0 and less then current page.
- On press enter button user will be navigate to the newly entered page. If page number is valid
- On focus out user will be navigate to the newly entered page. If page number is valid 
- If user do not change page nothing happen, he can exit navigation text field by focus out or pressing enter key

Issue https://github.com/mitodl/lore/issues/513
@pdpinch @giocalitri 

screen shot 2015-08-19 at 5 01 51 pm

screen shot 2015-08-19 at 5 01 55 pm

screen shot 2015-08-19 at 5 02 04 pm

screen shot 2015-08-19 at 5 02 16 pm

### CODE REVIEW

**Comment by ShawnMilo** [comment]
Minor usability points:
- The text box is too small; two-digit numbers are cut off, and for three digit numbers, the third digit doesn't appear on the screen.

Maybe small, but worth mentioning:
- I don't think it's obvious that one is expected to click on the "page x of n" text, although that's a fairly minor training issue.
- After selecting the page number you want, you can presss `<ENTER>` or click away from the widget, but it doesn't seem obvious.

**Comment by amir-qayyum-khan** [comment]
@ShawnMilo any suggestion on these points?

> - I don't think it's obvious that one is expected to click on the "page x of n" text, although that's a fairly  minor training issue.
> - After selecting the page number you want, you can presss <ENTER> or click away from the widget, but it doesn't seem obvious.

**Comment by ShawnMilo** [comment]
For the first one, what if the box was always there, so it would have the left and right arrows, with "page x of n" in the center, with "x" always being a text box? It wouldn't look as pretty, but would be more obvious.

As for the second one, I don't know if it's a good idea, but maybe show "press `ENTER` to view page" or something could appear when the user has clicked into the box, and disappear when they leave the box or press Enter.

I'm not a UI or UX expert though; someone else should weigh in as well. Any recommendations, @pdpinch?

**Comment by pdpinch** [comment]
I didn't want to delay this waiting for UX input, but it will eventually get UX input. 

For now, it can be an "advanced" feature that requires a little user training. 

I would like the box to be big enough to type 3 numbers though. 
- Peter

**Comment by ShawnMilo** [comment]
Okay. So once the box is enlarged I think it'll be good to merge.

**Comment by amir-qayyum-khan** [comment]
let me do that quickly.

**Comment by amir-qayyum-khan** [comment]
Done @ShawnMilo

**Comment by ShawnMilo** [comment]
It looks good. I'll merge after Travis passes. :o)

**Comment by amir-qayyum-khan** [comment]
sure :)

**Pull request merged**
