### PR TITLE
Updated Django to 1.8.3

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by carsongee** [comment]
https://docs.djangoproject.com/en/1.8/releases/1.8.3/

**Comment by giocalitri** [comment]
I did a quick regression and everything looks fine to me
(maybe a second opinion is better)

**Comment by carsongee** [comment]
Go ahead and merge this then, we can roll back if we discover new issues, but I'd like to prevent the security issue it addresses

**Comment by giocalitri** [comment]
ok

**Pull request merged**
