### PR TITLE
Changes to accommodate docker 1.9.0

### PR DESCRIPTION
**Pull request by jamiefolsom**
- Remove HOST_IP export.
- Quote booleans.
- Hard code port value.

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@noisecapella care to have a look? cc: @pwilkins

**Comment by pwilkins** [comment]
What is a sufficient acceptance test for this change?  Is it enough that the container can run LORE?

**Comment by jamiefolsom** [comment]
Right, this just lets LORE work on docker 1.9.0, so if `docker-compose up` works, this PR has done its job.

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
